name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    # Required for notebook rendering
    - id: install_pandoc
      run: sudo apt-get install pandoc
    # Build and deploy the sphinx documentation
    - id: github-pages-deployment
      uses: sphinx-notes/pages@v3
      with:
        python_version: 3.12
        publish: true
        documentation_path: ./docs/source
        requirements_path: ./docs/source/requirements.txt
